name: Haskell CI

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check packages
        run: |
          nix flake check

      - name: Build packages
        run: |
          # Build all packages for the current system
          nix build .#

      - name: Build devShells
        run: |
          # Build all devShells for the current system
          nix develop .# -c cabal test
          cd example
          nix develop ..#example -c cabal build

